
import com.sun.istack.internal.logging.Logger;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.Date;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Smktelkom
 */
public class frmTambah extends javax.swing.JFrame {

    /**
     * Creates new form frmTambah
     */
    public frmTambah() {
        initComponents();
        setTanggal();
        setJam();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labeltgl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labeljam = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtKasir = new javax.swing.JTextField();
        txtBarang = new javax.swing.JTextField();
        txtJumlah = new javax.swing.JTextField();
        txtSatuan = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOutput = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnPrint = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnClear = new javax.swing.JToggleButton();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel1.setText("Toko Buku");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, -10, 160, 70);

        labeltgl.setText("Tanggal");
        jPanel1.add(labeltgl);
        labeltgl.setBounds(590, 10, 120, 30);

        jLabel2.setFont(new java.awt.Font("Gisha", 0, 18)); // NOI18N
        jLabel2.setText("ONE PIECE");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 40, 120, 50);

        labeljam.setText("Jam");
        jPanel1.add(labeljam);
        labeljam.setBounds(590, 40, 130, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 730, 90);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Swis721 BT", 1, 12)); // NOI18N
        jLabel4.setText("ID Barang");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 0, 110, 40);
        jPanel2.add(txtID);
        txtID.setBounds(10, 30, 170, 30);

        jLabel5.setFont(new java.awt.Font("Swis721 BT", 1, 12)); // NOI18N
        jLabel5.setText("Nama Kasir");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 50, 110, 40);

        jLabel6.setFont(new java.awt.Font("Swis721 BT", 1, 12)); // NOI18N
        jLabel6.setText("Nama Barang");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 100, 110, 40);

        jLabel7.setFont(new java.awt.Font("Swis721 BT", 1, 12)); // NOI18N
        jLabel7.setText("Jumlah");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 150, 110, 40);

        jLabel8.setFont(new java.awt.Font("Swis721 BT", 1, 12)); // NOI18N
        jLabel8.setText("Harga per Satuan");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(10, 200, 110, 40);

        jLabel9.setFont(new java.awt.Font("Swis721 BT", 1, 12)); // NOI18N
        jLabel9.setText("Total Harga");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(650, 260, 110, 40);
        jPanel2.add(txtKasir);
        txtKasir.setBounds(10, 80, 170, 30);
        jPanel2.add(txtBarang);
        txtBarang.setBounds(10, 130, 170, 30);
        jPanel2.add(txtJumlah);
        txtJumlah.setBounds(10, 180, 170, 30);
        jPanel2.add(txtSatuan);
        txtSatuan.setBounds(10, 230, 170, 30);

        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        jPanel2.add(txtTotal);
        txtTotal.setBounds(470, 290, 250, 50);

        tblOutput.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "IDBarang", "NamaKasir", "NamaBarang", "Jumlah", "HargaSatuan", "TotalHarga"
            }
        ));
        jScrollPane1.setViewportView(tblOutput);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(210, 10, 510, 250);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 90, 730, 360);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        btnPrint.setFont(new java.awt.Font("Gisha", 1, 12)); // NOI18N
        btnPrint.setText("PRINT");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        jPanel3.add(btnPrint);
        btnPrint.setBounds(590, 20, 80, 30);

        btnSave.setFont(new java.awt.Font("Gisha", 1, 12)); // NOI18N
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel3.add(btnSave);
        btnSave.setBounds(50, 20, 80, 30);

        btnRefresh.setFont(new java.awt.Font("Gisha", 1, 12)); // NOI18N
        btnRefresh.setText("REFRESH");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        jPanel3.add(btnRefresh);
        btnRefresh.setBounds(300, 20, 100, 30);

        btnClear.setFont(new java.awt.Font("Gisha", 1, 12)); // NOI18N
        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel3.add(btnClear);
        btnClear.setBounds(450, 20, 80, 30);

        btnDelete.setFont(new java.awt.Font("Gisha", 1, 12)); // NOI18N
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel3.add(btnDelete);
        btnDelete.setBounds(180, 20, 80, 30);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 450, 730, 70);

        setBounds(0, 0, 746, 560);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Struk Belanja");
        MessageFormat footer = new MessageFormat("Page (0, number, integer)     ");
        try {
            tblOutput.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        } catch (java.awt.print.PrinterException e) {
            System.err.format("Cannot print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        if(txtID.getText().equals("") || txtKasir.getText().equals("") || txtBarang.getText().equals("") 
            || txtJumlah.getText().equals("") || txtSatuan.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error",
            JOptionPane.WARNING_MESSAGE);
        } else {
            
            int hb;
            int jml;
            int tot;
            int diskon=10;
            int akhir;
            int max = 100000;
            
            String hkotor = txtSatuan.getText();
            hb = Integer.parseInt(hkotor);
            String jumlh = txtJumlah.getText();
            jml = Integer.parseInt(jumlh);
            
            tot = hb * jml;
            if (tot > max) {
                int semifnl = (tot * diskon / 100);
                akhir = tot - semifnl;
            }else{
                akhir = tot;
                diskon = 0;
            }
            
            
            String SQL = "INSERT INTO tabel_transaksi (id_barang, nama_kasir, nama_barang, jumlah_barang, harga_satuan, total_hb)"
                    + "VALUES('"+txtID.getText()
                    +"', '"+txtKasir.getText()
                    +"', '"+txtBarang.getText()
                    +"', '"+txtJumlah.getText()
                    +"', '"+txtSatuan.getText()
                    +"', '"+akhir+"')";
            String hargaTot = Integer.toString(akhir);
            txtTotal.setText(hargaTot);
            
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal ditambahkan", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
            
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        selectData();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtID.setText("");
        txtKasir.setText("");
        txtBarang.setText("");
        txtJumlah.setText("");
        txtSatuan.setText("");
        txtTotal.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int baris = tblOutput.getSelectedRow();
        if (baris != -1) {
            String ID = tblOutput.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM tabel_transaksi WHERE id_barang='"+ID+"'";
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih Baris Data Terlebih Dahulu", "Error", JOptionPane.WARNING_MESSAGE);
        }
//        int baris = tblOutput.getSelectedRow();
//        if (baris != -1) {
//            String ID = tblOutput.getValueAt(baris, 0).toString();
//            String SQL = "DELETE FROM tabel_transaksi WHERE id_barang='"+ID+"'";
//            int status = KoneksiDB.execute(SQL);
//            if (status == 1) {
//                JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
//            } else {
//                JOptionPane.showMessageDialog(this, "Data gagal dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
//            }
//        } else {
//            JOptionPane.showMessageDialog(this, "Pilih Baris Data Terlebih Dahulu", "Error", JOptionPane.WARNING_MESSAGE);
//        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTambah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTambah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTambah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTambah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTambah().setVisible(true);
            }
        });
    }
    
    public void setTanggal() {
        java.util.Date now = new java.util.Date();
        java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("dd/MM/yyyy");
        labeltgl.setText(kal.format(now));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labeljam;
    private javax.swing.JLabel labeltgl;
    private javax.swing.JTable tblOutput;
    private javax.swing.JTextField txtBarang;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtKasir;
    private javax.swing.JTextField txtSatuan;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
        String kolom[] = {"IDBarang", "NamaKasir", "NamaBarang", "Jumlah", "HargaSatuan", "TotalHarga"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM tabel_transaksi";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try {
            while (rs.next()) {
                String ID = rs.getString(2);
                String NamaKasir = rs.getString(3);
                String NamaBarang = rs.getString(4);
                String Jumlah = rs.getString(5);
                String HargaSatuan = rs.getString(6);
                String Total = rs.getString(7);
                String data[] = {ID, NamaKasir, NamaBarang, Jumlah, HargaSatuan, Total};
                dtm.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmTambah.class).log(Level.SEVERE, null, ex);
        }
        tblOutput.setModel(dtm);
       //To change body of generated methods, choose Tools | Templates.
    }
    
    String nol_jam="";
    String nol_menit="";
    String nol_detik="";
    public void setJam() {
        ActionListener taskPerformer = new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                Date dt = new Date();
                int nilai_jam = dt.getHours();
                int nilai_menit = dt.getMinutes();
                int nilai_detik = dt.getSeconds();
                if (nilai_jam <= 9) {
                    nol_jam = "0";
                }
                if (nilai_menit <= 9) {
                    nol_menit = "0";
                }
                if (nilai_detik <= 9) {
                    nol_detik = "0";
                }
                
                String jam = nol_jam + Integer.toString(nilai_jam);
                String menit = nol_menit + Integer.toString(nilai_menit);
                String detik = nol_detik + Integer.toString(nilai_detik);
                labeljam.setText("Jam " + jam + ":" + menit + ":" + detik);
            }
        };
        new Timer(100, taskPerformer).start();
    }
}
